replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: show-env.dev.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  Environment: dev
  name: env-show

image:
  tag: sha256:8313713c0f3f7d10781c8551f18e5e435014462d0c0d017e641fa3d76d7a3b4e
