postgresql:
  enabled: false

externalDatabase:
  host: cnpg-database-rw.cloudnative-pg.svc.cluster.local
  user: app
  database: app
  existingSecret: pg-secret
  existingSecretPasswordKey: password

auth:
  ## @param auth.adminUser Keycloak administrator user
  ##
  adminUser: admin
  ## @param auth.adminPassword Keycloak administrator password for the new user
  ##
  # adminPassword: ""
  ## @param auth.existingSecret Existing secret containing Keycloak admin password
  ##
  existingSecret: pg-secret
  ## @param auth.passwordSecretKey Key where the Keycloak admin password is being stored inside the existing secret.
  ##
  passwordSecretKey: password


  # port: 5432
  # password: ""
  # existingSecretHostKey: ""
  # existingSecretPortKey: ""
  # existingSecretUserKey: ""
  # existingSecretDatabaseKey: ""
